spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leave_manager_interface?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
    username: root
    password: azerty1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false # Enable/disable display of SQL queries
        format_sql: true # Format displayed SQL queries
